version: 1.0.{build}
clone_folder: C:\Fruit
environment:
  PYTHON3_PATH: C:\Python36
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MINGW_PATH: 'C:\MinGW\bin'
    CMAKE_PATH: 'C:\Program Files (x86)\CMake\bin'
    CMAKE_GENERATOR: 'MinGW Makefiles'
    VCVARSALL_DIR: ''
    ADDITIONAL_CMAKE_ARGS: '-DFRUIT_USES_BOOST=False'
    CONFIGURATION: Debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin'
    CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
    VCVARSALL_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build'
    ADDITIONAL_CMAKE_ARGS: '-DFRUIT_USES_BOOST=False'
    CONFIGURATION: Debug

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MINGW_PATH: 'C:\MinGW\bin'
    CMAKE_PATH: 'C:\Program Files (x86)\CMake\bin'
    CMAKE_GENERATOR: 'MinGW Makefiles'
    VCVARSALL_DIR: ''
    ADDITIONAL_CMAKE_ARGS: '-DFRUIT_USES_BOOST=False'
    CONFIGURATION: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MINGW_PATH: 'C:\MinGW\bin'
    CMAKE_PATH: 'C:\Program Files (x86)\CMake\bin'
    CMAKE_GENERATOR: 'MinGW Makefiles'
    VCVARSALL_DIR: ''
    ADDITIONAL_CMAKE_ARGS: '-DBOOST_DIR=C:\Libraries\boost_1_63_0'
    CONFIGURATION: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin'
    CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
    VCVARSALL_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build'
    ADDITIONAL_CMAKE_ARGS: '-DFRUIT_USES_BOOST=False'
    CONFIGURATION: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MINGW_PATH: 'C:\MinGW\bin'
    CMAKE_PATH: 'C:\Program Files (x86)\CMake\bin'
    CMAKE_GENERATOR: 'MinGW Makefiles'
    VCVARSALL_DIR: ''
    ADDITIONAL_CMAKE_ARGS: '-DBOOST_DIR=C:\Libraries\boost_1_63_0 -DBUILD_SHARED_LIBS=False'
    CONFIGURATION: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin'
    CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
    VCVARSALL_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build'
    ADDITIONAL_CMAKE_ARGS: '-DFRUIT_USES_BOOST=False -DBUILD_SHARED_LIBS=False'
    CONFIGURATION: Release
build_script:
- cmd: cmd /c C:\Fruit\extras\scripts\postsubmit.bat
